### ISSUE TITLE
librdata cannot read rdata and rds files produced by R 3.6

### ISSUE THREAD

**Issue by ofajardo** [WizardMac/librdata#23] opened 2019-07-06 07:59 UTC
Reading rdata files produced by R 3.5 is fine (test_r35.Rdata) but fails for rdata files produced by R 3.6 (test_r36.Rdata) with error code 9 (Unable to open file). These files were produced on windows.

Interestingly in my hands it fails for rds files both produced in 3.5 and 3.6 (examples attached), however pyreadr is reading 3.5 fine but fails for 3.6. I'm using the slight modified version of librdata by @jonathonlove (jamovi) that compiles with visual studio. sample files also produced on windows.

This referes to the issue https://github.com/ofajardo/pyreadr/issues/10

[r35vs36.zip](https://github.com/WizardMac/librdata/files/3364519/r35vs36.zip)

**Comment by ofajardo** [comment] 2019-07-06 13:51
I also checked with files produced by R 3.5 and 3.6 on linux. In this case, in my hands, librdata cannot read any of them. Am I missing something?
[r35_36_linux.zip](https://github.com/WizardMac/librdata/files/3364720/r35_36_linux.zip)

**Comment by ofajardo** [comment] 2019-07-06 14:15
the discrepancies between the latest librdata version and latest pyreadr version may be also because pyreadr is behind librdata (I'm using commit b7ca1252b670d60a6e8d3c8ce6fcc8ab3b43d6ab) from April.

**Comment by evanmiller** [comment] 2019-07-07 11:55
Thanks for the report - I am able to reproduce the issue on `master`. For both the Windows and Linux files provided, the 3.5 files are parsed correctly, but the 3.6 files are not.

Please note that the Jamovi repository has not been updated since January - this may explain why the 3.5 files aren't opening for you.

I will look into the 3.6 files today.

**Comment by ofajardo** [comment] 2019-07-07 12:58
Thanks!
Weird, actually pyreadr (I merged librdata april commit with jamovi manually) is opening 3.5 fine and it is librdata (readEx.c) the one not doing it for me. I'll try again once your fixes are out.

**Comment by ofajardo** [comment] 2019-07-07 13:01
Btw, how do you test? If something different than readEx.c maybe you could share that?

**Comment by evanmiller** [comment] 2019-07-07 13:36
Make sure that readEx.c is linked against an up-to-date librdata. Sometimes there will be an old librdata.so in /usr/local, leading to confusion.

I test by linking against my main proprietary applications - can't share, sorry!

**Comment by evanmiller** [comment] 2019-07-07 13:36
Should be fixed in https://github.com/WizardMac/librdata/commit/0b41fb66e47bfdb6f73d964ba5ef54db8a14c4b4

**Comment by evanmiller** [comment] 2019-07-07 14:58
It would help me if you could upload a 3.6 Windows file with some non-ASCII data in it. Windows uses Latin-1 by default, and I'd like to make sure that UTF-8 is being delivered to the text handlers. Thanks.

**Comment by ofajardo** [comment] 2019-07-07 15:33
Attached the files with non-ascii characters (R 3.6 on windows). Indeed librdata cannot read them.

Regarding the original issues I reported, all solved now, I can read 3.5 and 3.6 from both pyreadr and librdata. Regarding librdata it was actually a compression error, compiling with -lz solved it. Thanks for the advice!

[non-ascii.zip](https://github.com/WizardMac/librdata/files/3365821/non-ascii.zip)

**Comment by evanmiller** [comment] 2019-07-07 16:05
Glad to hear the original files are opening for you now.

Okay, non-ASCII string vectors should work now. If you find other places where strings are not converted properly, please open a new issue.

**Closed by evanmiller** 2019-07-07 16:05 UTC
