### ISSUE TITLE
Unable to read RDS file which contains a list of trained caret ML model and R dataframe 

### ISSUE THREAD

**Issue by 86mm86** [WizardMac/librdata#30] opened 2020-05-05 14:55 UTC
When using pyreadr package in order to read a RDS file I get the error 

> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyreadr\pyreadr.py in read_r(path, use_objects, timezone)
>      38     if timezone:
>      39         parser.set_timezone(timezone)
> ---> 40     parser.parse(path)
>      41 
>      42     result = OrderedDict()
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyreadr\librdata.pyx in pyreadr.librdata.Parser.parse()
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyreadr\librdata.pyx in pyreadr.librdata.Parser.parse()
> 
> LibrdataError: Unable to read from file

The RDS file contains a list which contains a trained RandomForest model (trained with the caret library - S3: train, train.formula), a dataframe (S3: data.frame) and a list.  

I can not share the RDS file due to data privacy issue.

Any help appreciated!

**Comment by evanmiller** [comment] 2020-05-05 15:20
Thank you for the report. However, without a sample RDS file that demonstrates the issue, there is nothing I can do.

Without more information I am considering this a duplicate of #29.

**Closed by evanmiller** 2020-05-05 15:20 UTC

**Comment by ofajardo** [comment] 2020-05-05 15:26
@86mm86 please read carefully the section "known limitations" in pyreadr, it states clearly that currently r lists are not read, and attempting to reading them can raise all kind of strange error messages, the one you mention apparently among them.

**Comment by 86mm86** [comment] 2020-05-05 16:12
Thank you!
